### ISSUE TITLE
Add a `source` USE flag for Rust source code inclusion

### ISSUE THREAD

**Issue by stratact** [Heather/gentoo-rust#149]
For people that use [Racer](https://github.com/phildawes/racer), having the source code included in the rust installation would be valuable for Auto completion.

**Comment by jauhien** [comment]
https://github.com/gentoo/gentoo-rust/issues/9

**Comment by himikof** [comment]
This should probably be reopened, because this is the main repository now. @Heather, what do you think?

FYI, this will be useful not only for racer users, intellij-rust plugin will require stdlib sources for completion as well. Having them included in the installation is much more convenient than downloading them manually (and then keeping multiple versions in sync).

**Comment by stratact** [comment]
May I please request this issue to be reopen. It was **never** solved in the first place.
