### ISSUE TITLE
Add USE="doc" to build documentation.

### ISSUE THREAD

**Issue by o01eg** [Heather/gentoo-rust#77]
I removed --disable-docs and successfully built rust with html documentation and even pdf reference.

**Comment by omasanori** [comment]
When I added `--disable-docs`, it accessed outside of sandboxes if LuaTeX (`dev-tex/luatex` or `app-text/texlive` with `luatex` USE flag) is installed, so it fails to build unless `FEATURES="-sandbox -user-sandbox"`. I'll try to do it with LuaTeX again.

Anyway, since version 1.0.0 is before very long, probably it is about time to attack this...

**Comment by o01eg** [comment]
I've just successfully emerged `=rust-9999` with `dev-tex/luatex` and `app-text/texlive luatex` installed.

**Comment by gentoo90** [comment]
`USE="doc"` is also needed for `rust-bin` which currently installs html docs by default.

**Comment by omasanori** [comment]
OK. I'll work on this. I'm sorry for delaying.

**Comment by omasanori** [comment]
reopened this since `rust-bin` also needs `doc` USE flag.

**Comment by oleid** [comment]
The rust-999 ebuild doesn't install the documentation for me. Only when removing the line

    rm "${D}/usr/share/doc/rust" -rf

I got the documentation installed.
