### ISSUE TITLE
Should we put cargo binary in path for dev-lang/rust-bin?

### ISSUE THREAD

**Issue by jauhien** [Heather/gentoo-rust#89]
`dev-lang/rust-bin` includes cargo binary at the moment. What is better:

* remove it during installation
* install unconditionally and make `dev-lang/rust-bin` block `dev-rust/cargo`
* install cargo binary conditionally with USE and make it a blocker in this case

See also https://bugs.gentoo.org/show_bug.cgi?id=541298

**Comment by williamh** [comment]
If they install rust-bin they should get everything rust-bin provides. I would vote for making rust-bin block dev-rust/cargo.

**Comment by jauhien** [comment]
@williamh: I have thought about it more and what you say looks reasonabl for me. Could you, please, change live rust-bin in overlay and alpha rust-bin in the tree appropriately? And add block to the cargo ebuild as well. As I'm travelling again and will have my developer computer in front of me only on Monday. Thanks.

**Comment by williamh** [comment]
@jauhien:
I can add the blockers in the overlay, but not in the main tree, because the cargo ebuild is not in the main tree.

Do you know how cargo is going to be handled upstream once there are releases of rust? What I mean is, do you know if it will have a separate tarball, or if it will be part of the rust source tarball?

**Comment by jauhien** [comment]
@williamh: I mean, add blocker to the cargo ebuild, not the rust-bin ebuild.

I have no idea what are the plans. At the moment cargo is not installed by the rust compiled from sources.
